version: "3.9"
services:
  mongo:
    image: mongo:4.2.23
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    volumes:
      - ./MQTT_broker_mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  sensor:
    build:
      context: ./IoT_devices
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "3001-3501:3000"
    links:
      - server
    depends_on:
      - mosquitto
    volumes:
      - ./IoT_devices:/home/app

  server:
    build:
      context: ./Cloud_service
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "3000:3000"
    links:
      - mosquitto
      - mongo
      - kafka
    depends_on:
      - mosquitto
      - mongo
      - kafka
    volumes:
      - ./Cloud_service:/home/app
      

  mongo_express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    links:
      - mongo
    depends_on:
      - mongo

  analytics_module:
    build:
      context: ./Analytics_module
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8010:8010"
    depends_on:
      - kafka
    links:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TOPIC_AUTO_CREATE: true
