version: "3.9"
services:
  mongo:
    image: mongo:4.2.23
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    volumes:
      - ./MQTT_broker_mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  sensor:
    build:
      context: ./IoT_devices
      dockerfile: Dockerfile.dev
    ports:
      - "3001-3501:3000"
    links:
      - server
    depends_on:
      - mosquitto
    volumes:
      - ./IoT_devices:/home/app

  server:
    build:
      context: ./Cloud_service
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - mosquitto
      - mongo
    depends_on:
      - mosquitto
      - mongo
    volumes:
      - ./Cloud_service:/home/app

  mongo_express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    links:
      - mongo
    depends_on:
      - mongo
